// Generated by https://quicktype.io

export interface QuestionsResponse {
  response_code: number;
  results:       Result[];
}

export interface Result {
  type:              Type;
  difficulty:        Difficulty;
  category:          Category;
  question:          string;
  correct_answer:    CorrectAnswer;
  incorrect_answers: CorrectAnswer[];
}

export enum Category {
  GeneralKnowledge = "General Knowledge",
}

export enum CorrectAnswer {
  False = "False",
  True = "True",
}

export enum Difficulty {
  Easy = "easy",
}

export enum Type {
  Boolean = "boolean",
}
